//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExempluConBazaDeDate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public song()
        {
            this.listening_history = new HashSet<listening_history>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public int artist_id { get; set; }
        public int album_id { get; set; }
        public string genre { get; set; }
    
        public virtual album album { get; set; }
        public virtual artist artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listening_history> listening_history { get; set; }
    }
}
